# Generated by Django 3.1.6 on 2021-02-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('position', models.CharField(max_length=10)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tat Date')),
                ('tat', models.CharField(choices=[('C', 'Cover Up'), ('F', 'Flash'), ('N', 'Custom')], default='C', max_length=1)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.artist')),
            ],
        ),
    ]
