# Generated by Django 3.1.6 on 2021-02-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tats',
            name='tat',
            field=models.CharField(choices=[('F', 'Flash'), ('N', 'Custom'), ('C', 'Cover Up')], default='F', max_length=1),
        ),
    ]
