# Generated by Django 3.1.6 on 2021-02-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210207_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tats',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
