# Generated by Django 3.1.6 on 2021-02-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210207_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deets',
            new_name='Flash',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='deets',
        ),
        migrations.AddField(
            model_name='artist',
            name='flash',
            field=models.ManyToManyField(to='main_app.Flash'),
        ),
    ]
