# Generated by Django 3.1.6 on 2021-02-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210208_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flash',
            name='location',
        ),
        migrations.RemoveField(
            model_name='flash',
            name='size',
        ),
    ]
