# Generated by Django 3.1.6 on 2021-02-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210208_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='flashs',
            new_name='flash',
        ),
    ]
