# Generated by Django 3.1.6 on 2021-02-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210208_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='instagram',
            field=models.CharField(default='off the grid', max_length=50),
        ),
    ]
