# Generated by Django 3.1.6 on 2021-02-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_artist_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
