# Generated by Django 3.1.6 on 2021-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210208_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='position',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flash',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
